spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db35shop
    username: root
    password: root2023
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    username: javalessons2024@gmail.com
    password: egmoyxcnbsbfoawu
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 60000